[functions]
node_bundler = "esbuild"  # Используем esbuild для сборки функций
external_node_modules = ["fastify", "aws-lambda-fastify"]
directory = "netlify/functions"  # Путь к функциям

[[redirects]]
from = "/"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
from = "/tags/*"
to = "/.netlify/functions/api"
status = 200

