# @baseUrl = http://localhost:8888
@baseUrl = https://competent-shockley-e44c09.netlify.app

###
GET {{baseUrl}}/api/ HTTP/1.1

###
POST {{baseUrl}}/api/ HTTP/1.1

###
POST {{baseUrl}}/api/ HTTP/1.1
Content-Type: application/json

{
    "myKey": "myValue"
}